name: Test YAML Action

on:
  issues:
    types: opened

jobs:
  test:
   runs-on: ubuntu-latest
   name: Extract Payload
   
   steps:
     - name: Checkout
       uses: actions/checkout@v2
       
     - name: Parse Issue Body
       uses: ./
       id: issue_body_parser
       with:
         template-path: .github/ISSUE_TEMPLATE/batch_data_ingestion_as_a_service_intake.md
         github_token: ${{ secrets.GITHUB_TOKEN }}
         issue_id: 1
         payload: yaml
     
     - name: Use Parsed Values
       env:
         DATA: ${{ steps.issue_body_parser.outputs.payload }}
         CONTENT_ID_VALUE: ${{ fromJSON(steps.issue_body_parser.outputs.payload).id }}
       run: >
         echo "$DATA\n"
         echo "ID: $CONTENT_ID_VALUE\n"
